# Problem Set 3: Solutions

Due **10 Feb 2021**

Note that there's usually more than one way to achive the same result. As such, these answers show just one (or two) possibilities. You can have a perfectly valid code which achieves the same but differs from below.

In [131]:
from IPython.core.interactiveshell import InteractiveShell  # This is to display all outputs in a cell
InteractiveShell.ast_node_interactivity = "all"             # not just the last one (can also be set in preferences)

### 1. Import the numpy package under the name `np` 
(**hint**: import … as …)

In [132]:
import numpy as np

### 2. Basics of array creation

Create an array:
 - of 10 zeros
 - of 10 zeros except the fifth entry is a 1
 - with values ranging from 7 to 28
 - with values ranging from 7 to 28, but only even numbers
 - with values ranging from 7 to 28, but in reverse order
 - of size 10 with values ranging from 0 to 1, evenly spaced, with both endpoints excluded
 - of size 50, with random integers between 0 and 10
     - use `bincount` and `argmax` to find the most frequently occurring value
 
 
 
**Hint**: You can use the indexing method `start:stop:step` (not specific to NumPy): it's a general slicing which says include elements from `start` (inclusive) to `stop` (not including) taking every `step` element. If `start` is omitted, this means start from the beginning; if `stop` is omitted, this means continue till the end of the sequence. Finally, negative step means count from the end. So, `::2` takes every other element `::3` every third, etc. Negative indexes read from the end forwards, so `::-1` reads in plain language: "take the whole sequence and read from the end using step 1."

In [133]:
zs=np.zeros(10)
print(zs)
zs[4]=1
print(zs)

ra=np.arange(29)
ra=ra[7:29]
print(ra)

ra_even=[]
for i in ra:
    if (i%2)==0:
        ra_even.append(i)
ra_even=np.array(ra_even, dtype='int64')
print(ra_even)

ra[1::2] #other way to do above function

sterev=[i for i in range(29)]
sterev=sterev[7:29]
sterev.reverse()
sterev=np.array(sterev,dtype='float64')
print(sterev)

osterev=ra[::-1] #other way of above function
osterev

tensiz=np.linspace(0,1,12)
tensiz=tensiz[1:11]
tensiz

fifsiz=np.random.randint(0, high=10, size=50, dtype=int)
numcount={}
for num in fifsiz:
        if str(num) not in numcount:
            numcount[str(num)]=1
        else:
            numcount[str(num)]+=1
numcount=list(numcount.items())
numcount

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[ 7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28]
[ 8 10 12 14 16 18 20 22 24 26 28]


array([ 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

[28. 27. 26. 25. 24. 23. 22. 21. 20. 19. 18. 17. 16. 15. 14. 13. 12. 11.
 10.  9.  8.  7.]


array([28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12,
       11, 10,  9,  8,  7])

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

[('1', 5),
 ('6', 5),
 ('3', 4),
 ('8', 5),
 ('0', 10),
 ('5', 5),
 ('2', 4),
 ('7', 6),
 ('9', 4),
 ('4', 2)]

### 3.  Multi-Dimensional Arrays

Create a:
 - 5x5 matrix with values from 0 to 24
 - 5x5 matrix with random values between 0 and 1
     - find the min and max values
     - find the mean
     - find the mean of each row (store this as a vertical vector (a (5x1 matrix)) **Hint**: keepdims=True

In [134]:
mat24=np.random.randint(0, high=24, size=25, dtype=int).reshape(5,5)
mat24

mat01=np.random.random(25).reshape(5,5)
mat01

np.min(mat01)
np.max(mat01)
np.mean(mat01)

mat01mean=mat01.mean(axis=1).reshape(5,1)
mat01mean

array([[17,  6, 23,  4, 13],
       [17,  9, 21, 11,  8],
       [10,  6, 22,  9, 13],
       [17, 11,  4,  6,  2],
       [17, 22, 14, 15, 18]])

array([[0.23591169, 0.27214648, 0.97021028, 0.94773531, 0.23436908],
       [0.51917398, 0.22618642, 0.22191914, 0.50605908, 0.96205308],
       [0.38367374, 0.38309427, 0.28563142, 0.49688073, 0.08094971],
       [0.08678141, 0.21627757, 0.29489648, 0.85798642, 0.88266075],
       [0.17956185, 0.1567345 , 0.71467958, 0.98763324, 0.53089972]])

0.08094970908161048

0.9876332407785158

0.46536423625437273

array([[0.53207457],
       [0.48707834],
       [0.32604597],
       [0.46772053],
       [0.51390178]])

### 4. How to find the closest value (to a given scalar) in a vector?
Write a function that takes an array and find the index (and the associated value) of the value closest to the mean.
Test on `x = np.random.random(12)`.

In [135]:
def closest_to_mean(arr):
    """
    input: arr, an np array of numeric types
    output: the index closed to the mean of the array
    """
    m=np.mean(arr)
    mdis=[]
    for i in arr:
        mdis.append(abs(m-i))
    mdis.sort()
    return [mdis[0], np.where(abs(arr-m)==mdis[0])]
        
    
    
x = np.random.random(12)
closest_to_mean(x)

[0.01706042794368534, (array([7], dtype=int64),)]

### 5. Boolean Indexing

Create a function `odd_v_even` which: 
 - Takes as input a 5x5 matrix and creates a new matrix, `x`, that is the same as the input matrix except with all even numbers negated. You can use either.
     -  Boolean Masking/Indexing
     -  `np.where(cond, if-arr, else-arr)`
 - The function should return the matrix `x` as well as how many rows of `x` have a sum greater than 0. **Hint**: To calculate how many rows have a sum >0, you can calculate sums across each row of `x`, then can use boolean indexing to get True and False values, then use sum to add Trues (1) and Falses (0).
 
Finally, create a 5x5 matrix, called `z`, of random integers between 0 and 10. Run this function on `z`.

In [235]:
def odd_v_even(m):
    """
    input: z is a 5x5 matrix (np object)
    output: (z, a) where x is a matrix with even values of z negated and a and int, the number of rows with sum >0
    """
    eve=m%2==0
    m[eve]=0
    absum=m.sum(axis=1)>0
    absumd={}
    for i in absum:
        if i not in absumd:
            absumd[i]=1
        else:
                absumd[i]+=1
    return (mat24,'there are '+str(absumd[True])+' rows greater than zero.')

In [236]:
z=np.random.randint(0, high=24, size=25, dtype=int).reshape(5,5)
odd_v_even(z)

(array([[17,  0, 11, 19,  0],
        [13, 11,  0, 17,  7],
        [ 5,  0,  0, 13,  0],
        [ 0,  5,  1, 17,  0],
        [ 0,  0,  0,  0, 13]]),
 'there are 4 rows greater than zero.')